### ISSUE TITLE
No module named 'coco'

### ISSUE THREAD

**Issue by x12901** [soumyaiitkgp/Custom_MaskRCNN#1]
Nice project.I tried to run 'demo.ipynb', but it gave me an error!
`sys.path.append(os.path.join(ROOT_DIR, "samples\\custom\\"))  # To find local version`
`import coco`

---------------------------------------------------------------------------

Using TensorFlow backend.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-0744aee4bbd6> in <module>()
     19 #sys.path.append(C:\ProgramData\Anaconda3\Lib\site-packages\pycocotools)
     20 sys.path.append(os.path.join(ROOT_DIR, "samples\\custom\\"))  # To find local version
---> 21 import coco
     22 #from samples.coco import coco
     23 get_ipython().run_line_magic('matplotlib', 'inline')

ModuleNotFoundError: No module named 'coco'

---------------------------------------------------------------------------

I tried using my local version and it didn't work.
`sys.path.append(C:\ProgramData\Anaconda3\Lib\site-packages\pycocotools)`

python :3.6.5
tensorflow :1.15.0
pycocotools:2.0.2
keras:2.0.8

**Comment by soumyaiitkgp** [comment]
Hi, @x12901 thank you for using this repository. I have fixed the error you encountered. Please let me know if it is working for you or not.

**Comment by x12901** [comment]
> Hi, @x12901 thank you for using this repository. I have fixed the error you encountered. Please let me know if it is working for you or not.

Now the demo is ready to run. Thank you！
