### ISSUE TITLE
Only display one class

### ISSUE THREAD

**Issue by x12901** [soumyaiitkgp/Custom_MaskRCNN#2]
I can only display one class, I think there may be a problem with custom.py.
`            num_ids=[]`
            `#Add the classes according to the requirement`
          `  for n in custom:`
              `  try:`
                  `  if n['label']=='object1':`
                     `   num_ids.append(1)`
                   ` elif n['label']=='object2':`
                       ` num_ids.append(2)`
           `     except:`
                `    pass`
 In custom.py ，num_ids is not being used.I read another article.[https://github.com/matterport/Mask_RCNN/issues/372#issuecomment-377010489](url)
Maybe this code should be changed.
`self.add_image(
                "custom",
                image_id=a['filename'],  # use file name as a unique image id
                path=image_path,
                width=width, height=height,
                polygons=polygons)`
`# Return mask, and array of class IDs of each instance. Since we have
        # one class ID only, we return an array of 1s
        return mask.astype(np.bool), np.ones([mask.shape[-1]], dtype=np.int32)`

**Comment by soumyaiitkgp** [comment]
I have updated the python code for custom.py file for more than one class masking. Please let me know if the problem persists.

**Comment by x12901** [comment]
> I have updated the python code for custom.py file for more than one class masking. Please let me know if the problem persists.

I retrained the image and the program now displays properly, thanks!

**Comment by soumyaiitkgp** [comment]
Hi, @x12901. I wanted feedback from your side about the repository. How easy was it to use and possible problem faced while making this repo work. Let me know your feedback [here.](Psoumyadav@gmail.com)

Please mention the subject of the email as 'soumyaiitkgp/Custom_MaskRCNN feedback'.
